#!/usr/bin/env bash
todo.sh list | while read -r line; do
   todo_id="$(echo $line | cut -d' ' -f1)"
   todo_label="$(echo $line | cut -d' ' -f2-)"
   todo_new_label=$(echo $todo_label | sed "s/\+[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]/+$(date -Idate)/g")
   todo.sh replace "$todo_id" "$todo_new_label"
done
